import {useEffect,useState,useMemo} from 'react';
import {collection,onSnapshot} from 'firebase/firestore';
import {db} from '../firebase';
import {workshopPost} from '../lib/workshopApi';
import {sizeParts} from '../lib/tyreWork';
import {isTyre,itemDescription,tyreData} from '../lib/tyrePresentation';
import TyreBrandLogo from './TyreBrandLogo';
export const PRICE_LEVELS=[['retail','Retail'],['special2Plus','2+ Special'],['xtra','Xtra'],['supply','Supply']];
export function stockLevelPrice(p,key='retail'){const explicit=p.priceLevels?.[key]??p[{retail:'retailIncVat',special2Plus:'special2PlusIncVat',xtra:'xtraIncVat',supply:'supplyIncVat'}[key]];if(explicit!==undefined&&Number(explicit)>0)return Number(explicit);const retail=Number(p.retailIncVat??p.priceLevels?.retail??p.pricing?.retail??0);return key==='special2Plus'?Math.max(0,retail-4.9992):key==='xtra'?retail*(retail<=198?.92:.96):key==='supply'?(Number(p.costExVat||0)+12)*1.2:retail;}
const key=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
export default function ItemSearch({initialCategory='all',onSelect,onClose,stockProducts,serviceMaster}){
 const [stock,setStock]=useState([]),[services,setServices]=useState([]),[search,setSearch]=useState(''),[category,setCategory]=useState(initialCategory),[partner,setPartner]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(stockProducts)return;return onSnapshot(collection(db,'stockProducts'),s=>setStock(s.docs.map(d=>({id:d.id,...d.data()}))),e=>setError(e.message));},[stockProducts]);
 useEffect(()=>{if(serviceMaster)return;return onSnapshot(collection(db,'serviceMaster'),s=>setServices(s.docs.map(d=>({id:d.id,...d.data()}))),e=>setError(e.message));},[serviceMaster]);
 const masters=serviceMaster||services;
 const results=useMemo(()=>{const term=key(search);if(term.length<2)return [];const rows=[...(stockProducts||stock).filter(p=>p.active!==false).map(p=>({...p,kind:'stock'})),...masters.filter(p=>p.active!==false).map(p=>({...p,kind:'service'})),...partner.map(p=>({...p,type:'tyre',category:'tyre',kind:'stock',source:'oak',description:itemDescription({...p,type:'tyre'})}))];return rows.filter(p=>(category==='all'||(category==='tyre'&&isTyre(p))||(category==='service'&&p.kind==='service')||(category==='part'&&p.kind==='stock'&&!isTyre(p)))&&key([p.sku,p.code,p.name,p.description,p.size,p.brand,p.pattern].join(' ')).includes(term)).slice(0,40);},[search,category,stockProducts,stock,masters,partner]);
 async function searchPartner(){setBusy(true);setError('');setPartner([]);try{const r=await workshopPost('adminMidasTyreSearchV2',sizeParts(search));setPartner(r.products||[]);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="itemSearchPanel"><div className="itemSearchControls"><select aria-label="Search item category" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All items</option><option value="tyre">Tyres</option><option value="service">Services</option><option value="part">Parts / other stock</option></select><input aria-label="Search order items" autoFocus value={search} placeholder="Size, brand, model, service or stock code…" onChange={e=>{setSearch(e.target.value);setPartner([]);}}/><button type="button" disabled={busy} onClick={searchPartner}>{busy?'Searching…':'Search partner tyres'}</button><button type="button" onClick={()=>{setSearch('');setPartner([]);setError('');}}>Clear</button>{onClose&&<button type="button" onClick={onClose}>Close</button>}</div>{error&&<p className="tfNotice" role="alert">{error}</p>}<div className="itemSearchResults">{results.map((p,i)=><article key={`${p.source||p.kind}-${p.id||p.sku||p.code}-${i}`} className="itemSearchResult">{isTyre(p)&&<TyreBrandLogo line={p}/>}<div className="itemSearchDescription"><strong>{itemDescription(p)}</strong><small>{p.sku||p.code} · {p.kind==='service'?'Service master':p.source==='oak'?'Partner stock':`Tyremen stock · ${Number(p.stockQty||0)} on hand`}</small>{isTyre(p)&&<div className="jobFitmentFlags">{tyreData(p).flags.map(f=><span key={f}>{f}</span>)}</div>}</div><div className="itemPriceChoices">{(p.kind==='service'?[['retail','Add']]:PRICE_LEVELS).map(([level,label])=><button type="button" key={level} onClick={()=>onSelect(p,p.kind,level,masters)}>{label}<b>£{(p.kind==='service'?Number(p.retailIncVat||0):stockLevelPrice(p,level)).toFixed(2)}</b></button>)}</div></article>)}{!results.length&&<p className="itemSearchEmpty">{key(search).length<2?'Enter a search to find stock or service master items.':'No items match. For live supply, enter a complete size and choose Search partner tyres.'}</p>}</div></section>;
}
