import {useEffect,useState} from 'react';
import {workshopPost} from '../lib/workshopApi';
const labels={mot:'MOT',service:'Servicing',tyres:'Tyres (whole booking)',alignment:'Wheel alignment',diagnostics:'Diagnostics',timing:'Cambelt / timing chain',clutch:'Clutch',brakes:'Brakes',airconR134a:'Air-con R134a',airconR1234yf:'Air-con R1234yf'};
export default function WorkshopDurationDefaults({date,onApplied}) {
 const [settings,setSettings]=useState(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [dirty,setDirty]=useState(false);
 useEffect(()=>{const controller=new AbortController();workshopPost('getWorkshopDurationDefaults',{},controller.signal).then(r=>setSettings(r.settings)).catch(e=>{if(!controller.signal.aborted)setMessage(e.message);});return()=>controller.abort();},[]);
 async function save(e){e.preventDefault();setBusy(true);setMessage('');try{const r=await workshopPost('saveWorkshopDurationDefaults',{settings});setSettings(r.settings);setDirty(false);setMessage('Duration defaults saved. Existing plans stay unchanged.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function apply(){setBusy(true);setMessage('');try{const r=await workshopPost('applyWorkshopDurationDefaults',{date});setMessage(`${r.count} unplanned bookings planned for ${date}.`);onApplied();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <form className="wbEditor" onSubmit={save}><h2>Default job durations</h2><p>Review these starter estimates before enabling. New bookings will receive a plan automatically; quantities of tyres do not multiply the duration. Unknown work and durations that conflict with a combined booking stay manual. Adjust individual jobs for the vehicle and work required.</p>{message&&<div className="wbNotice" role="status">{message}</div>}{settings&&<><label className="wbEnable"><input type="checkbox" checked={settings.enabled} onChange={e=>{setSettings({...settings,enabled:e.target.checked});setDirty(true);}}/>Enable automatic planning for new bookings</label><div className="wbDurationFields">{Object.entries(labels).map(([key,label])=><label key={key}>{label} (minutes)<input type="number" min="5" max="720" step="1" value={settings.minutes[key]} required onChange={e=>{setSettings({...settings,minutes:{...settings.minutes,[key]:Number(e.target.value)}});setDirty(true);}}/></label>)}</div><div className="wbInlineActions"><button type="submit" disabled={busy}>{busy?'Saving…':'Save duration defaults'}</button><button type="button" disabled={busy||dirty||!settings.enabled} onClick={apply}>Apply to unplanned jobs · {date}</button></div><p>Saved manual plans and completed jobs are never replaced. This sets expected work times; booking capacity still uses the shared diary rules.</p></>}</form>;
}
