import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {workshopPost} from '../lib/workshopApi';
import {londonDate,shiftDate} from '../lib/workshopTime';
function rangeFor(key){const today=londonDate();if(key==='yesterday'){const date=shiftDate(today,-1);return {from:date,to:date};}if(key==='week'){const day=new Date(today+'T12:00:00Z').getUTCDay();return {from:shiftDate(today,-((day+6)%7)),to:today};}if(key==='month')return {from:today.slice(0,8)+'01',to:today};return {from:today,to:today};}
export default function WorkshopHistory(){
  const [preset,setPreset]=useState('week');const [range,setRange]=useState(()=>rangeFor('week'));const [draft,setDraft]=useState(()=>rangeFor('week'));
  const [jobs,setJobs]=useState([]);const [filter,setFilter]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [refresh,setRefresh]=useState(0);const [page,setPage]=useState(0);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setJobs([]);setPage(0);workshopPost('getWorkshopHistory',range,controller.signal).then(data=>{if(!controller.signal.aborted)setJobs(data.jobs);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[range,refresh]);
  const matches=useMemo(()=>jobs.filter(j=>[j.registration,j.service,j.technician,j.invoiceNumber].join(' ').toLowerCase().includes(filter.toLowerCase())),[jobs,filter]);const pages=Math.max(1,Math.ceil(matches.length/50));const actualPage=Math.min(page,pages-1);
  function choose(key){setPreset(key);if(key!=='custom'){const value=rangeFor(key);setRange(value);setDraft(value);}}
  return <section className="wbListPanel"><div className="wbListToolbar"><div><h2>Completed history</h2><span>Completed {range.from} – {range.to} · {matches.length} jobs</span></div><input aria-label="Search completed jobs" placeholder="Registration, work, technician or invoice…" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}/></div><div className="wbHistoryFilters">{[['yesterday','Yesterday'],['week','This week'],['month','This month'],['custom','Custom range']].map(([key,label])=><button type="button" key={key} aria-pressed={preset===key} onClick={()=>choose(key)}>{label}</button>)}<button type="button" onClick={()=>setRefresh(v=>v+1)}>Refresh history</button></div>{preset==='custom'&&<form className="wbRangeForm" onSubmit={e=>{e.preventDefault();setRange({...draft});}}><label>From<input type="date" value={draft.from} max={draft.to} required onChange={e=>setDraft({...draft,from:e.target.value})}/></label><label>To<input type="date" value={draft.to} min={draft.from} required onChange={e=>setDraft({...draft,to:e.target.value})}/></label><button type="submit">Search dates</button></form>}<p className="wbHistoryNote">Dates refer to completion. Older jobs without a completion timestamp use their booking date. Records and invoices are retained.</p>{error&&<div className="wbNotice" role="alert">{error}</div>}<div className="sysTableScroll"><table className="wbOperationsTable"><thead><tr><th>Vehicle / work</th><th>Completed</th><th>Booked</th><th>Technician</th><th>Invoice</th><th>View</th></tr></thead><tbody>{matches.slice(actualPage*50,actualPage*50+50).map(j=><tr key={j.id}><td><b className="sysPlate">{j.registration||'NO REG'}</b><strong>{j.service||'Workshop work'}</strong></td><td>{j.completedDate}</td><td>{j.date} · {j.time}</td><td>{j.technician||'—'}</td><td>{j.invoiceNumber||'No invoice linked'}</td><td>{j.invoiceId?<Link to={`/sales?invoice=${encodeURIComponent(j.invoiceId)}`}>View invoice</Link>:<Link to={`/orders?job=${encodeURIComponent(j.id)}`}>View job</Link>}</td></tr>)}</tbody></table></div>{!matches.length&&<div className="sysEmpty">{loading?'Loading completed jobs…':error?'History could not be loaded.':'No completed jobs in this range.'}</div>}{pages>1&&<div className="wbInlineActions"><button disabled={actualPage===0} onClick={()=>setPage(actualPage-1)}>Previous</button><span>Page {actualPage+1} of {pages}</span><button disabled={actualPage===pages-1} onClick={()=>setPage(actualPage+1)}>Next</button></div>}</section>;
}
